/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsSection: typeof import('./src/components/AnalyticsSection.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconFallback: typeof import('./src/components/IconFallback.vue')['default']
    MetricsCards: typeof import('./src/components/MetricsCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartIcon: typeof import('./src/components/SmartIcon.vue')['default']
    TeamProgressSection: typeof import('./src/components/TeamProgressSection.vue')['default']
  }
}
